#!/usr/bin/env ruby

require 'yaml'
require 'time'
require 'open3'

chrome = 'Mozilla/5.0 (Windows NT 6.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/41.0.2228.0 Safari/537.36'


heartland = 'heartland-heartbleed-solutions.com'
www_heartland = 'www.heartland-heartbleed-solutions.com'
heartland_ip = '82.82.93.93'

rc4_sha = 'RC4-SHA'
aes256_sha = 'AES256-SHA'


PARAM_KEYS = %i[
  http_verb tls cipher is_secure user_agent host header_host
]

TRACE_FILE = 'trace.tmp'

get = 'get'
head = 'head'


tries = [

  #  http-verb  tls-version  cipher       secure?  user-agent  host            header-host
  [  get,       1.0,         nil,         true,    chrome,     heartland,      nil,              ],
  [  get,       1.1,         nil,         true,    chrome,     heartland,      nil,              ],
  [  get,       1.2,         nil,         true,    chrome,     heartland,      nil,              ],
  [  get,       1.0,         nil,         false,   chrome,     heartland,      nil,              ],
  [  get,       1.1,         nil,         false,   chrome,     heartland,      nil,              ],
  [  get,       1.2,         nil,         false,   chrome,     heartland,      nil,              ],
  [  head,      1.0,         nil,         true,    chrome,     heartland,      nil,              ],
  [  head,      1.1,         nil,         true,    chrome,     heartland,      nil,              ],
  [  head,      1.2,         nil,         true,    chrome,     heartland,      nil,              ],
  [  head,      1.0,         nil,         false,   chrome,     heartland,      nil,              ],
  [  head,      1.1,         nil,         false,   chrome,     heartland,      nil,              ],
  [  head,      1.2,         nil,         false,   chrome,     heartland,      nil,              ],
  [  get,       1.0,         nil,         true,    chrome,     heartland,      heartland,        ],
  [  get,       1.1,         nil,         true,    chrome,     heartland,      heartland,        ],
  [  get,       1.2,         nil,         true,    chrome,     heartland,      heartland,        ],
  [  get,       1.0,         nil,         false,   chrome,     heartland,      heartland,        ],
  [  get,       1.1,         nil,         false,   chrome,     heartland,      heartland,        ],
  [  get,       1.2,         nil,         false,   chrome,     heartland,      heartland,        ],
  [  head,      1.0,         nil,         true,    chrome,     heartland,      heartland,        ],
  [  head,      1.1,         nil,         true,    chrome,     heartland,      heartland,        ],
  [  head,      1.2,         nil,         true,    chrome,     heartland,      heartland,        ],
  [  head,      1.0,         nil,         false,   chrome,     heartland,      heartland,        ],
  [  head,      1.1,         nil,         false,   chrome,     heartland,      heartland,        ],
  [  head,      1.2,         nil,         false,   chrome,     heartland,      heartland,        ],
  [  get,       1.0,         nil,         true,    chrome,     heartland,      heartland_ip,     ],
  [  get,       1.1,         nil,         true,    chrome,     heartland,      heartland_ip,     ],
  [  get,       1.2,         nil,         true,    chrome,     heartland,      heartland_ip,     ],
  [  get,       1.0,         nil,         false,   chrome,     heartland,      heartland_ip,     ],
  [  get,       1.1,         nil,         false,   chrome,     heartland,      heartland_ip,     ],
  [  get,       1.2,         nil,         false,   chrome,     heartland,      heartland_ip,     ],
  [  head,      1.0,         nil,         true,    chrome,     heartland,      heartland_ip,     ],
  [  head,      1.1,         nil,         true,    chrome,     heartland,      heartland_ip,     ],
  [  head,      1.2,         nil,         true,    chrome,     heartland,      heartland_ip,     ],
  [  head,      1.0,         nil,         false,   chrome,     heartland,      heartland_ip,     ],
  [  head,      1.1,         nil,         false,   chrome,     heartland,      heartland_ip,     ],
  [  head,      1.2,         nil,         false,   chrome,     heartland,      heartland_ip,     ],
  [  get,       1.0,         nil,         true,    chrome,     heartland,      www_heartland,    ],
  [  get,       1.1,         nil,         true,    chrome,     heartland,      www_heartland,    ],
  [  get,       1.2,         nil,         true,    chrome,     heartland,      www_heartland,    ],
  [  get,       1.0,         nil,         false,   chrome,     heartland,      www_heartland,    ],
  [  get,       1.1,         nil,         false,   chrome,     heartland,      www_heartland,    ],
  [  get,       1.2,         nil,         false,   chrome,     heartland,      www_heartland,    ],
  [  head,      1.0,         nil,         true,    chrome,     heartland,      www_heartland,    ],
  [  head,      1.1,         nil,         true,    chrome,     heartland,      www_heartland,    ],
  [  head,      1.2,         nil,         true,    chrome,     heartland,      www_heartland,    ],
  [  head,      1.0,         nil,         false,   chrome,     heartland,      www_heartland,    ],
  [  head,      1.1,         nil,         false,   chrome,     heartland,      www_heartland,    ],
  [  head,      1.2,         nil,         false,   chrome,     heartland,      www_heartland,    ],
  [  get,       1.0,         rc4_sha,     true,    chrome,     heartland,      nil,              ],
  [  get,       1.1,         rc4_sha,     true,    chrome,     heartland,      nil,              ],
  [  get,       1.2,         rc4_sha,     true,    chrome,     heartland,      nil,              ],
  [  get,       1.0,         rc4_sha,     false,   chrome,     heartland,      nil,              ],
  [  get,       1.1,         rc4_sha,     false,   chrome,     heartland,      nil,              ],
  [  get,       1.2,         rc4_sha,     false,   chrome,     heartland,      nil,              ],
  [  head,      1.0,         rc4_sha,     true,    chrome,     heartland,      nil,              ],
  [  head,      1.1,         rc4_sha,     true,    chrome,     heartland,      nil,              ],
  [  head,      1.2,         rc4_sha,     true,    chrome,     heartland,      nil,              ],
  [  head,      1.0,         rc4_sha,     false,   chrome,     heartland,      nil,              ],
  [  head,      1.1,         rc4_sha,     false,   chrome,     heartland,      nil,              ],
  [  head,      1.2,         rc4_sha,     false,   chrome,     heartland,      nil,              ],
  [  get,       1.0,         rc4_sha,     true,    chrome,     heartland,      heartland,        ],
  [  get,       1.1,         rc4_sha,     true,    chrome,     heartland,      heartland,        ],
  [  get,       1.2,         rc4_sha,     true,    chrome,     heartland,      heartland,        ],
  [  get,       1.0,         rc4_sha,     false,   chrome,     heartland,      heartland,        ],
  [  get,       1.1,         rc4_sha,     false,   chrome,     heartland,      heartland,        ],
  [  get,       1.2,         rc4_sha,     false,   chrome,     heartland,      heartland,        ],
  [  head,      1.0,         rc4_sha,     true,    chrome,     heartland,      heartland,        ],
  [  head,      1.1,         rc4_sha,     true,    chrome,     heartland,      heartland,        ],
  [  head,      1.2,         rc4_sha,     true,    chrome,     heartland,      heartland,        ],
  [  head,      1.0,         rc4_sha,     false,   chrome,     heartland,      heartland,        ],
  [  head,      1.1,         rc4_sha,     false,   chrome,     heartland,      heartland,        ],
  [  head,      1.2,         rc4_sha,     false,   chrome,     heartland,      heartland,        ],
  [  get,       1.0,         rc4_sha,     true,    chrome,     heartland,      heartland_ip,     ],
  [  get,       1.1,         rc4_sha,     true,    chrome,     heartland,      heartland_ip,     ],
  [  get,       1.2,         rc4_sha,     true,    chrome,     heartland,      heartland_ip,     ],
  [  get,       1.0,         rc4_sha,     false,   chrome,     heartland,      heartland_ip,     ],
  [  get,       1.1,         rc4_sha,     false,   chrome,     heartland,      heartland_ip,     ],
  [  get,       1.2,         rc4_sha,     false,   chrome,     heartland,      heartland_ip,     ],
  [  head,      1.0,         rc4_sha,     true,    chrome,     heartland,      heartland_ip,     ],
  [  head,      1.1,         rc4_sha,     true,    chrome,     heartland,      heartland_ip,     ],
  [  head,      1.2,         rc4_sha,     true,    chrome,     heartland,      heartland_ip,     ],
  [  head,      1.0,         rc4_sha,     false,   chrome,     heartland,      heartland_ip,     ],
  [  head,      1.1,         rc4_sha,     false,   chrome,     heartland,      heartland_ip,     ],
  [  head,      1.2,         rc4_sha,     false,   chrome,     heartland,      heartland_ip,     ],
  [  get,       1.0,         rc4_sha,     true,    chrome,     heartland,      www_heartland,    ],
  [  get,       1.1,         rc4_sha,     true,    chrome,     heartland,      www_heartland,    ],
  [  get,       1.2,         rc4_sha,     true,    chrome,     heartland,      www_heartland,    ],
  [  get,       1.0,         rc4_sha,     false,   chrome,     heartland,      www_heartland,    ],
  [  get,       1.1,         rc4_sha,     false,   chrome,     heartland,      www_heartland,    ],
  [  get,       1.2,         rc4_sha,     false,   chrome,     heartland,      www_heartland,    ],
  [  head,      1.0,         rc4_sha,     true,    chrome,     heartland,      www_heartland,    ],
  [  head,      1.1,         rc4_sha,     true,    chrome,     heartland,      www_heartland,    ],
  [  head,      1.2,         rc4_sha,     true,    chrome,     heartland,      www_heartland,    ],
  [  head,      1.0,         rc4_sha,     false,   chrome,     heartland,      www_heartland,    ],
  [  head,      1.1,         rc4_sha,     false,   chrome,     heartland,      www_heartland,    ],
  [  head,      1.2,         rc4_sha,     false,   chrome,     heartland,      www_heartland,    ],
  [  get,       1.0,         aes256_sha,  true,    chrome,     heartland,      nil,              ],
  [  get,       1.1,         aes256_sha,  true,    chrome,     heartland,      nil,              ],
  [  get,       1.2,         aes256_sha,  true,    chrome,     heartland,      nil,              ],
  [  get,       1.0,         aes256_sha,  false,   chrome,     heartland,      nil,              ],
  [  get,       1.1,         aes256_sha,  false,   chrome,     heartland,      nil,              ],
  [  get,       1.2,         aes256_sha,  false,   chrome,     heartland,      nil,              ],
  [  head,      1.0,         aes256_sha,  true,    chrome,     heartland,      nil,              ],
  [  head,      1.1,         aes256_sha,  true,    chrome,     heartland,      nil,              ],
  [  head,      1.2,         aes256_sha,  true,    chrome,     heartland,      nil,              ],
  [  head,      1.0,         aes256_sha,  false,   chrome,     heartland,      nil,              ],
  [  head,      1.1,         aes256_sha,  false,   chrome,     heartland,      nil,              ],
  [  head,      1.2,         aes256_sha,  false,   chrome,     heartland,      nil,              ],
  [  get,       1.0,         aes256_sha,  true,    chrome,     heartland,      heartland,        ],
  [  get,       1.1,         aes256_sha,  true,    chrome,     heartland,      heartland,        ],
  [  get,       1.2,         aes256_sha,  true,    chrome,     heartland,      heartland,        ],
  [  get,       1.0,         aes256_sha,  false,   chrome,     heartland,      heartland,        ],
  [  get,       1.1,         aes256_sha,  false,   chrome,     heartland,      heartland,        ],
  [  get,       1.2,         aes256_sha,  false,   chrome,     heartland,      heartland,        ],
  [  head,      1.0,         aes256_sha,  true,    chrome,     heartland,      heartland,        ],
  [  head,      1.1,         aes256_sha,  true,    chrome,     heartland,      heartland,        ],
  [  head,      1.2,         aes256_sha,  true,    chrome,     heartland,      heartland,        ],
  [  head,      1.0,         aes256_sha,  false,   chrome,     heartland,      heartland,        ],
  [  head,      1.1,         aes256_sha,  false,   chrome,     heartland,      heartland,        ],
  [  head,      1.2,         aes256_sha,  false,   chrome,     heartland,      heartland,        ],
  [  get,       1.0,         aes256_sha,  true,    chrome,     heartland,      heartland_ip,     ],
  [  get,       1.1,         aes256_sha,  true,    chrome,     heartland,      heartland_ip,     ],
  [  get,       1.2,         aes256_sha,  true,    chrome,     heartland,      heartland_ip,     ],
  [  get,       1.0,         aes256_sha,  false,   chrome,     heartland,      heartland_ip,     ],
  [  get,       1.1,         aes256_sha,  false,   chrome,     heartland,      heartland_ip,     ],
  [  get,       1.2,         aes256_sha,  false,   chrome,     heartland,      heartland_ip,     ],
  [  head,      1.0,         aes256_sha,  true,    chrome,     heartland,      heartland_ip,     ],
  [  head,      1.1,         aes256_sha,  true,    chrome,     heartland,      heartland_ip,     ],
  [  head,      1.2,         aes256_sha,  true,    chrome,     heartland,      heartland_ip,     ],
  [  head,      1.0,         aes256_sha,  false,   chrome,     heartland,      heartland_ip,     ],
  [  head,      1.1,         aes256_sha,  false,   chrome,     heartland,      heartland_ip,     ],
  [  head,      1.2,         aes256_sha,  false,   chrome,     heartland,      heartland_ip,     ],
  [  get,       1.0,         aes256_sha,  true,    chrome,     heartland,      www_heartland,    ],
  [  get,       1.1,         aes256_sha,  true,    chrome,     heartland,      www_heartland,    ],
  [  get,       1.2,         aes256_sha,  true,    chrome,     heartland,      www_heartland,    ],
  [  get,       1.0,         aes256_sha,  false,   chrome,     heartland,      www_heartland,    ],
  [  get,       1.1,         aes256_sha,  false,   chrome,     heartland,      www_heartland,    ],
  [  get,       1.2,         aes256_sha,  false,   chrome,     heartland,      www_heartland,    ],
  [  head,      1.0,         aes256_sha,  true,    chrome,     heartland,      www_heartland,    ],
  [  head,      1.1,         aes256_sha,  true,    chrome,     heartland,      www_heartland,    ],
  [  head,      1.2,         aes256_sha,  true,    chrome,     heartland,      www_heartland,    ],
  [  head,      1.0,         aes256_sha,  false,   chrome,     heartland,      www_heartland,    ],
  [  head,      1.1,         aes256_sha,  false,   chrome,     heartland,      www_heartland,    ],
  [  head,      1.2,         aes256_sha,  false,   chrome,     heartland,      www_heartland,    ],
  [  get,       1.0,         nil,         true,    chrome,     www_heartland,  nil,              ],
  [  get,       1.1,         nil,         true,    chrome,     www_heartland,  nil,              ],
  [  get,       1.2,         nil,         true,    chrome,     www_heartland,  nil,              ],
  [  get,       1.0,         nil,         false,   chrome,     www_heartland,  nil,              ],
  [  get,       1.1,         nil,         false,   chrome,     www_heartland,  nil,              ],
  [  get,       1.2,         nil,         false,   chrome,     www_heartland,  nil,              ],
  [  head,      1.0,         nil,         true,    chrome,     www_heartland,  nil,              ],
  [  head,      1.1,         nil,         true,    chrome,     www_heartland,  nil,              ],
  [  head,      1.2,         nil,         true,    chrome,     www_heartland,  nil,              ],
  [  head,      1.0,         nil,         false,   chrome,     www_heartland,  nil,              ],
  [  head,      1.1,         nil,         false,   chrome,     www_heartland,  nil,              ],
  [  head,      1.2,         nil,         false,   chrome,     www_heartland,  nil,              ],
  [  get,       1.0,         nil,         true,    chrome,     www_heartland,  heartland,        ],
  [  get,       1.1,         nil,         true,    chrome,     www_heartland,  heartland,        ],
  [  get,       1.2,         nil,         true,    chrome,     www_heartland,  heartland,        ],
  [  get,       1.0,         nil,         false,   chrome,     www_heartland,  heartland,        ],
  [  get,       1.1,         nil,         false,   chrome,     www_heartland,  heartland,        ],
  [  get,       1.2,         nil,         false,   chrome,     www_heartland,  heartland,        ],
  [  head,      1.0,         nil,         true,    chrome,     www_heartland,  heartland,        ],
  [  head,      1.1,         nil,         true,    chrome,     www_heartland,  heartland,        ],
  [  head,      1.2,         nil,         true,    chrome,     www_heartland,  heartland,        ],
  [  head,      1.0,         nil,         false,   chrome,     www_heartland,  heartland,        ],
  [  head,      1.1,         nil,         false,   chrome,     www_heartland,  heartland,        ],
  [  head,      1.2,         nil,         false,   chrome,     www_heartland,  heartland,        ],
  [  get,       1.0,         nil,         true,    chrome,     www_heartland,  heartland_ip,     ],
  [  get,       1.1,         nil,         true,    chrome,     www_heartland,  heartland_ip,     ],
  [  get,       1.2,         nil,         true,    chrome,     www_heartland,  heartland_ip,     ],
  [  get,       1.0,         nil,         false,   chrome,     www_heartland,  heartland_ip,     ],
  [  get,       1.1,         nil,         false,   chrome,     www_heartland,  heartland_ip,     ],
  [  get,       1.2,         nil,         false,   chrome,     www_heartland,  heartland_ip,     ],
  [  head,      1.0,         nil,         true,    chrome,     www_heartland,  heartland_ip,     ],
  [  head,      1.1,         nil,         true,    chrome,     www_heartland,  heartland_ip,     ],
  [  head,      1.2,         nil,         true,    chrome,     www_heartland,  heartland_ip,     ],
  [  head,      1.0,         nil,         false,   chrome,     www_heartland,  heartland_ip,     ],
  [  head,      1.1,         nil,         false,   chrome,     www_heartland,  heartland_ip,     ],
  [  head,      1.2,         nil,         false,   chrome,     www_heartland,  heartland_ip,     ],
  [  get,       1.0,         nil,         true,    chrome,     www_heartland,  www_heartland,    ],
  [  get,       1.1,         nil,         true,    chrome,     www_heartland,  www_heartland,    ],
  [  get,       1.2,         nil,         true,    chrome,     www_heartland,  www_heartland,    ],
  [  get,       1.0,         nil,         false,   chrome,     www_heartland,  www_heartland,    ],
  [  get,       1.1,         nil,         false,   chrome,     www_heartland,  www_heartland,    ],
  [  get,       1.2,         nil,         false,   chrome,     www_heartland,  www_heartland,    ],
  [  head,      1.0,         nil,         true,    chrome,     www_heartland,  www_heartland,    ],
  [  head,      1.1,         nil,         true,    chrome,     www_heartland,  www_heartland,    ],
  [  head,      1.2,         nil,         true,    chrome,     www_heartland,  www_heartland,    ],
  [  head,      1.0,         nil,         false,   chrome,     www_heartland,  www_heartland,    ],
  [  head,      1.1,         nil,         false,   chrome,     www_heartland,  www_heartland,    ],
  [  head,      1.2,         nil,         false,   chrome,     www_heartland,  www_heartland,    ],
  [  get,       1.0,         rc4_sha,     true,    chrome,     www_heartland,  nil,              ],
  [  get,       1.1,         rc4_sha,     true,    chrome,     www_heartland,  nil,              ],
  [  get,       1.2,         rc4_sha,     true,    chrome,     www_heartland,  nil,              ],
  [  get,       1.0,         rc4_sha,     false,   chrome,     www_heartland,  nil,              ],
  [  get,       1.1,         rc4_sha,     false,   chrome,     www_heartland,  nil,              ],
  [  get,       1.2,         rc4_sha,     false,   chrome,     www_heartland,  nil,              ],
  [  head,      1.0,         rc4_sha,     true,    chrome,     www_heartland,  nil,              ],
  [  head,      1.1,         rc4_sha,     true,    chrome,     www_heartland,  nil,              ],
  [  head,      1.2,         rc4_sha,     true,    chrome,     www_heartland,  nil,              ],
  [  head,      1.0,         rc4_sha,     false,   chrome,     www_heartland,  nil,              ],
  [  head,      1.1,         rc4_sha,     false,   chrome,     www_heartland,  nil,              ],
  [  head,      1.2,         rc4_sha,     false,   chrome,     www_heartland,  nil,              ],
  [  get,       1.0,         rc4_sha,     true,    chrome,     www_heartland,  heartland,        ],
  [  get,       1.1,         rc4_sha,     true,    chrome,     www_heartland,  heartland,        ],
  [  get,       1.2,         rc4_sha,     true,    chrome,     www_heartland,  heartland,        ],
  [  get,       1.0,         rc4_sha,     false,   chrome,     www_heartland,  heartland,        ],
  [  get,       1.1,         rc4_sha,     false,   chrome,     www_heartland,  heartland,        ],
  [  get,       1.2,         rc4_sha,     false,   chrome,     www_heartland,  heartland,        ],
  [  head,      1.0,         rc4_sha,     true,    chrome,     www_heartland,  heartland,        ],
  [  head,      1.1,         rc4_sha,     true,    chrome,     www_heartland,  heartland,        ],
  [  head,      1.2,         rc4_sha,     true,    chrome,     www_heartland,  heartland,        ],
  [  head,      1.0,         rc4_sha,     false,   chrome,     www_heartland,  heartland,        ],
  [  head,      1.1,         rc4_sha,     false,   chrome,     www_heartland,  heartland,        ],
  [  head,      1.2,         rc4_sha,     false,   chrome,     www_heartland,  heartland,        ],
  [  get,       1.0,         rc4_sha,     true,    chrome,     www_heartland,  heartland_ip,     ],
  [  get,       1.1,         rc4_sha,     true,    chrome,     www_heartland,  heartland_ip,     ],
  [  get,       1.2,         rc4_sha,     true,    chrome,     www_heartland,  heartland_ip,     ],
  [  get,       1.0,         rc4_sha,     false,   chrome,     www_heartland,  heartland_ip,     ],
  [  get,       1.1,         rc4_sha,     false,   chrome,     www_heartland,  heartland_ip,     ],
  [  get,       1.2,         rc4_sha,     false,   chrome,     www_heartland,  heartland_ip,     ],
  [  head,      1.0,         rc4_sha,     true,    chrome,     www_heartland,  heartland_ip,     ],
  [  head,      1.1,         rc4_sha,     true,    chrome,     www_heartland,  heartland_ip,     ],
  [  head,      1.2,         rc4_sha,     true,    chrome,     www_heartland,  heartland_ip,     ],
  [  head,      1.0,         rc4_sha,     false,   chrome,     www_heartland,  heartland_ip,     ],
  [  head,      1.1,         rc4_sha,     false,   chrome,     www_heartland,  heartland_ip,     ],
  [  head,      1.2,         rc4_sha,     false,   chrome,     www_heartland,  heartland_ip,     ],
  [  get,       1.0,         rc4_sha,     true,    chrome,     www_heartland,  www_heartland,    ],
  [  get,       1.1,         rc4_sha,     true,    chrome,     www_heartland,  www_heartland,    ],
  [  get,       1.2,         rc4_sha,     true,    chrome,     www_heartland,  www_heartland,    ],
  [  get,       1.0,         rc4_sha,     false,   chrome,     www_heartland,  www_heartland,    ],
  [  get,       1.1,         rc4_sha,     false,   chrome,     www_heartland,  www_heartland,    ],
  [  get,       1.2,         rc4_sha,     false,   chrome,     www_heartland,  www_heartland,    ],
  [  head,      1.0,         rc4_sha,     true,    chrome,     www_heartland,  www_heartland,    ],
  [  head,      1.1,         rc4_sha,     true,    chrome,     www_heartland,  www_heartland,    ],
  [  head,      1.2,         rc4_sha,     true,    chrome,     www_heartland,  www_heartland,    ],
  [  head,      1.0,         rc4_sha,     false,   chrome,     www_heartland,  www_heartland,    ],
  [  head,      1.1,         rc4_sha,     false,   chrome,     www_heartland,  www_heartland,    ],
  [  head,      1.2,         rc4_sha,     false,   chrome,     www_heartland,  www_heartland,    ],
  [  get,       1.0,         aes256_sha,  true,    chrome,     www_heartland,  nil,              ],
  [  get,       1.1,         aes256_sha,  true,    chrome,     www_heartland,  nil,              ],
  [  get,       1.2,         aes256_sha,  true,    chrome,     www_heartland,  nil,              ],
  [  get,       1.0,         aes256_sha,  false,   chrome,     www_heartland,  nil,              ],
  [  get,       1.1,         aes256_sha,  false,   chrome,     www_heartland,  nil,              ],
  [  get,       1.2,         aes256_sha,  false,   chrome,     www_heartland,  nil,              ],
  [  head,      1.0,         aes256_sha,  true,    chrome,     www_heartland,  nil,              ],
  [  head,      1.1,         aes256_sha,  true,    chrome,     www_heartland,  nil,              ],
  [  head,      1.2,         aes256_sha,  true,    chrome,     www_heartland,  nil,              ],
  [  head,      1.0,         aes256_sha,  false,   chrome,     www_heartland,  nil,              ],
  [  head,      1.1,         aes256_sha,  false,   chrome,     www_heartland,  nil,              ],
  [  head,      1.2,         aes256_sha,  false,   chrome,     www_heartland,  nil,              ],
  [  get,       1.0,         aes256_sha,  true,    chrome,     www_heartland,  heartland,        ],
  [  get,       1.1,         aes256_sha,  true,    chrome,     www_heartland,  heartland,        ],
  [  get,       1.2,         aes256_sha,  true,    chrome,     www_heartland,  heartland,        ],
  [  get,       1.0,         aes256_sha,  false,   chrome,     www_heartland,  heartland,        ],
  [  get,       1.1,         aes256_sha,  false,   chrome,     www_heartland,  heartland,        ],
  [  get,       1.2,         aes256_sha,  false,   chrome,     www_heartland,  heartland,        ],
  [  head,      1.0,         aes256_sha,  true,    chrome,     www_heartland,  heartland,        ],
  [  head,      1.1,         aes256_sha,  true,    chrome,     www_heartland,  heartland,        ],
  [  head,      1.2,         aes256_sha,  true,    chrome,     www_heartland,  heartland,        ],
  [  head,      1.0,         aes256_sha,  false,   chrome,     www_heartland,  heartland,        ],
  [  head,      1.1,         aes256_sha,  false,   chrome,     www_heartland,  heartland,        ],
  [  head,      1.2,         aes256_sha,  false,   chrome,     www_heartland,  heartland,        ],
  [  get,       1.0,         aes256_sha,  true,    chrome,     www_heartland,  heartland_ip,     ],
  [  get,       1.1,         aes256_sha,  true,    chrome,     www_heartland,  heartland_ip,     ],
  [  get,       1.2,         aes256_sha,  true,    chrome,     www_heartland,  heartland_ip,     ],
  [  get,       1.0,         aes256_sha,  false,   chrome,     www_heartland,  heartland_ip,     ],
  [  get,       1.1,         aes256_sha,  false,   chrome,     www_heartland,  heartland_ip,     ],
  [  get,       1.2,         aes256_sha,  false,   chrome,     www_heartland,  heartland_ip,     ],
  [  head,      1.0,         aes256_sha,  true,    chrome,     www_heartland,  heartland_ip,     ],
  [  head,      1.1,         aes256_sha,  true,    chrome,     www_heartland,  heartland_ip,     ],
  [  head,      1.2,         aes256_sha,  true,    chrome,     www_heartland,  heartland_ip,     ],
  [  head,      1.0,         aes256_sha,  false,   chrome,     www_heartland,  heartland_ip,     ],
  [  head,      1.1,         aes256_sha,  false,   chrome,     www_heartland,  heartland_ip,     ],
  [  head,      1.2,         aes256_sha,  false,   chrome,     www_heartland,  heartland_ip,     ],
  [  get,       1.0,         aes256_sha,  true,    chrome,     www_heartland,  www_heartland,    ],
  [  get,       1.1,         aes256_sha,  true,    chrome,     www_heartland,  www_heartland,    ],
  [  get,       1.2,         aes256_sha,  true,    chrome,     www_heartland,  www_heartland,    ],
  [  get,       1.0,         aes256_sha,  false,   chrome,     www_heartland,  www_heartland,    ],
  [  get,       1.1,         aes256_sha,  false,   chrome,     www_heartland,  www_heartland,    ],
  [  get,       1.2,         aes256_sha,  false,   chrome,     www_heartland,  www_heartland,    ],
  [  head,      1.0,         aes256_sha,  true,    chrome,     www_heartland,  www_heartland,    ],
  [  head,      1.1,         aes256_sha,  true,    chrome,     www_heartland,  www_heartland,    ],
  [  head,      1.2,         aes256_sha,  true,    chrome,     www_heartland,  www_heartland,    ],
  [  head,      1.0,         aes256_sha,  false,   chrome,     www_heartland,  www_heartland,    ],
  [  head,      1.1,         aes256_sha,  false,   chrome,     www_heartland,  www_heartland,    ],
  [  head,      1.2,         aes256_sha,  false,   chrome,     www_heartland,  www_heartland,    ],
  [  get,       1.0,         nil,         true,    chrome,     heartland_ip,   nil,              ],
  [  get,       1.1,         nil,         true,    chrome,     heartland_ip,   nil,              ],
  [  get,       1.2,         nil,         true,    chrome,     heartland_ip,   nil,              ],
  [  get,       1.0,         nil,         false,   chrome,     heartland_ip,   nil,              ],
  [  get,       1.1,         nil,         false,   chrome,     heartland_ip,   nil,              ],
  [  get,       1.2,         nil,         false,   chrome,     heartland_ip,   nil,              ],
  [  head,      1.0,         nil,         true,    chrome,     heartland_ip,   nil,              ],
  [  head,      1.1,         nil,         true,    chrome,     heartland_ip,   nil,              ],
  [  head,      1.2,         nil,         true,    chrome,     heartland_ip,   nil,              ],
  [  head,      1.0,         nil,         false,   chrome,     heartland_ip,   nil,              ],
  [  head,      1.1,         nil,         false,   chrome,     heartland_ip,   nil,              ],
  [  head,      1.2,         nil,         false,   chrome,     heartland_ip,   nil,              ],
  [  get,       1.0,         nil,         true,    chrome,     heartland_ip,   heartland,        ],
  [  get,       1.1,         nil,         true,    chrome,     heartland_ip,   heartland,        ],
  [  get,       1.2,         nil,         true,    chrome,     heartland_ip,   heartland,        ],
  [  get,       1.0,         nil,         false,   chrome,     heartland_ip,   heartland,        ],
  [  get,       1.1,         nil,         false,   chrome,     heartland_ip,   heartland,        ],
  [  get,       1.2,         nil,         false,   chrome,     heartland_ip,   heartland,        ],
  [  head,      1.0,         nil,         true,    chrome,     heartland_ip,   heartland,        ],
  [  head,      1.1,         nil,         true,    chrome,     heartland_ip,   heartland,        ],
  [  head,      1.2,         nil,         true,    chrome,     heartland_ip,   heartland,        ],
  [  head,      1.0,         nil,         false,   chrome,     heartland_ip,   heartland,        ],
  [  head,      1.1,         nil,         false,   chrome,     heartland_ip,   heartland,        ],
  [  head,      1.2,         nil,         false,   chrome,     heartland_ip,   heartland,        ],
  [  get,       1.0,         nil,         true,    chrome,     heartland_ip,   heartland_ip,     ],
  [  get,       1.1,         nil,         true,    chrome,     heartland_ip,   heartland_ip,     ],
  [  get,       1.2,         nil,         true,    chrome,     heartland_ip,   heartland_ip,     ],
  [  get,       1.0,         nil,         false,   chrome,     heartland_ip,   heartland_ip,     ],
  [  get,       1.1,         nil,         false,   chrome,     heartland_ip,   heartland_ip,     ],
  [  get,       1.2,         nil,         false,   chrome,     heartland_ip,   heartland_ip,     ],
  [  head,      1.0,         nil,         true,    chrome,     heartland_ip,   heartland_ip,     ],
  [  head,      1.1,         nil,         true,    chrome,     heartland_ip,   heartland_ip,     ],
  [  head,      1.2,         nil,         true,    chrome,     heartland_ip,   heartland_ip,     ],
  [  head,      1.0,         nil,         false,   chrome,     heartland_ip,   heartland_ip,     ],
  [  head,      1.1,         nil,         false,   chrome,     heartland_ip,   heartland_ip,     ],
  [  head,      1.2,         nil,         false,   chrome,     heartland_ip,   heartland_ip,     ],
  [  get,       1.0,         nil,         true,    chrome,     heartland_ip,   www_heartland,    ],
  [  get,       1.1,         nil,         true,    chrome,     heartland_ip,   www_heartland,    ],
  [  get,       1.2,         nil,         true,    chrome,     heartland_ip,   www_heartland,    ],
  [  get,       1.0,         nil,         false,   chrome,     heartland_ip,   www_heartland,    ],
  [  get,       1.1,         nil,         false,   chrome,     heartland_ip,   www_heartland,    ],
  [  get,       1.2,         nil,         false,   chrome,     heartland_ip,   www_heartland,    ],
  [  head,      1.0,         nil,         true,    chrome,     heartland_ip,   www_heartland,    ],
  [  head,      1.1,         nil,         true,    chrome,     heartland_ip,   www_heartland,    ],
  [  head,      1.2,         nil,         true,    chrome,     heartland_ip,   www_heartland,    ],
  [  head,      1.0,         nil,         false,   chrome,     heartland_ip,   www_heartland,    ],
  [  head,      1.1,         nil,         false,   chrome,     heartland_ip,   www_heartland,    ],
  [  head,      1.2,         nil,         false,   chrome,     heartland_ip,   www_heartland,    ],
  [  get,       1.0,         rc4_sha,     true,    chrome,     heartland_ip,   nil,              ],
  [  get,       1.1,         rc4_sha,     true,    chrome,     heartland_ip,   nil,              ],
  [  get,       1.2,         rc4_sha,     true,    chrome,     heartland_ip,   nil,              ],
  [  get,       1.0,         rc4_sha,     false,   chrome,     heartland_ip,   nil,              ],
  [  get,       1.1,         rc4_sha,     false,   chrome,     heartland_ip,   nil,              ],
  [  get,       1.2,         rc4_sha,     false,   chrome,     heartland_ip,   nil,              ],
  [  head,      1.0,         rc4_sha,     true,    chrome,     heartland_ip,   nil,              ],
  [  head,      1.1,         rc4_sha,     true,    chrome,     heartland_ip,   nil,              ],
  [  head,      1.2,         rc4_sha,     true,    chrome,     heartland_ip,   nil,              ],
  [  head,      1.0,         rc4_sha,     false,   chrome,     heartland_ip,   nil,              ],
  [  head,      1.1,         rc4_sha,     false,   chrome,     heartland_ip,   nil,              ],
  [  head,      1.2,         rc4_sha,     false,   chrome,     heartland_ip,   nil,              ],
  [  get,       1.0,         rc4_sha,     true,    chrome,     heartland_ip,   heartland,        ],
  [  get,       1.1,         rc4_sha,     true,    chrome,     heartland_ip,   heartland,        ],
  [  get,       1.2,         rc4_sha,     true,    chrome,     heartland_ip,   heartland,        ],
  [  get,       1.0,         rc4_sha,     false,   chrome,     heartland_ip,   heartland,        ],
  [  get,       1.1,         rc4_sha,     false,   chrome,     heartland_ip,   heartland,        ],
  [  get,       1.2,         rc4_sha,     false,   chrome,     heartland_ip,   heartland,        ],
  [  head,      1.0,         rc4_sha,     true,    chrome,     heartland_ip,   heartland,        ],
  [  head,      1.1,         rc4_sha,     true,    chrome,     heartland_ip,   heartland,        ],
  [  head,      1.2,         rc4_sha,     true,    chrome,     heartland_ip,   heartland,        ],
  [  head,      1.0,         rc4_sha,     false,   chrome,     heartland_ip,   heartland,        ],
  [  head,      1.1,         rc4_sha,     false,   chrome,     heartland_ip,   heartland,        ],
  [  head,      1.2,         rc4_sha,     false,   chrome,     heartland_ip,   heartland,        ],
  [  get,       1.0,         rc4_sha,     true,    chrome,     heartland_ip,   heartland_ip,     ],
  [  get,       1.1,         rc4_sha,     true,    chrome,     heartland_ip,   heartland_ip,     ],
  [  get,       1.2,         rc4_sha,     true,    chrome,     heartland_ip,   heartland_ip,     ],
  [  get,       1.0,         rc4_sha,     false,   chrome,     heartland_ip,   heartland_ip,     ],
  [  get,       1.1,         rc4_sha,     false,   chrome,     heartland_ip,   heartland_ip,     ],
  [  get,       1.2,         rc4_sha,     false,   chrome,     heartland_ip,   heartland_ip,     ],
  [  head,      1.0,         rc4_sha,     true,    chrome,     heartland_ip,   heartland_ip,     ],
  [  head,      1.1,         rc4_sha,     true,    chrome,     heartland_ip,   heartland_ip,     ],
  [  head,      1.2,         rc4_sha,     true,    chrome,     heartland_ip,   heartland_ip,     ],
  [  head,      1.0,         rc4_sha,     false,   chrome,     heartland_ip,   heartland_ip,     ],
  [  head,      1.1,         rc4_sha,     false,   chrome,     heartland_ip,   heartland_ip,     ],
  [  head,      1.2,         rc4_sha,     false,   chrome,     heartland_ip,   heartland_ip,     ],
  [  get,       1.0,         rc4_sha,     true,    chrome,     heartland_ip,   www_heartland,    ],
  [  get,       1.1,         rc4_sha,     true,    chrome,     heartland_ip,   www_heartland,    ],
  [  get,       1.2,         rc4_sha,     true,    chrome,     heartland_ip,   www_heartland,    ],
  [  get,       1.0,         rc4_sha,     false,   chrome,     heartland_ip,   www_heartland,    ],
  [  get,       1.1,         rc4_sha,     false,   chrome,     heartland_ip,   www_heartland,    ],
  [  get,       1.2,         rc4_sha,     false,   chrome,     heartland_ip,   www_heartland,    ],
  [  head,      1.0,         rc4_sha,     true,    chrome,     heartland_ip,   www_heartland,    ],
  [  head,      1.1,         rc4_sha,     true,    chrome,     heartland_ip,   www_heartland,    ],
  [  head,      1.2,         rc4_sha,     true,    chrome,     heartland_ip,   www_heartland,    ],
  [  head,      1.0,         rc4_sha,     false,   chrome,     heartland_ip,   www_heartland,    ],
  [  head,      1.1,         rc4_sha,     false,   chrome,     heartland_ip,   www_heartland,    ],
  [  head,      1.2,         rc4_sha,     false,   chrome,     heartland_ip,   www_heartland,    ],
  [  get,       1.0,         aes256_sha,  true,    chrome,     heartland_ip,   nil,              ],
  [  get,       1.1,         aes256_sha,  true,    chrome,     heartland_ip,   nil,              ],
  [  get,       1.2,         aes256_sha,  true,    chrome,     heartland_ip,   nil,              ],
  [  get,       1.0,         aes256_sha,  false,   chrome,     heartland_ip,   nil,              ],
  [  get,       1.1,         aes256_sha,  false,   chrome,     heartland_ip,   nil,              ],
  [  get,       1.2,         aes256_sha,  false,   chrome,     heartland_ip,   nil,              ],
  [  head,      1.0,         aes256_sha,  true,    chrome,     heartland_ip,   nil,              ],
  [  head,      1.1,         aes256_sha,  true,    chrome,     heartland_ip,   nil,              ],
  [  head,      1.2,         aes256_sha,  true,    chrome,     heartland_ip,   nil,              ],
  [  head,      1.0,         aes256_sha,  false,   chrome,     heartland_ip,   nil,              ],
  [  head,      1.1,         aes256_sha,  false,   chrome,     heartland_ip,   nil,              ],
  [  head,      1.2,         aes256_sha,  false,   chrome,     heartland_ip,   nil,              ],
  [  get,       1.0,         aes256_sha,  true,    chrome,     heartland_ip,   heartland,        ],
  [  get,       1.1,         aes256_sha,  true,    chrome,     heartland_ip,   heartland,        ],
  [  get,       1.2,         aes256_sha,  true,    chrome,     heartland_ip,   heartland,        ],
  [  get,       1.0,         aes256_sha,  false,   chrome,     heartland_ip,   heartland,        ],
  [  get,       1.1,         aes256_sha,  false,   chrome,     heartland_ip,   heartland,        ],
  [  get,       1.2,         aes256_sha,  false,   chrome,     heartland_ip,   heartland,        ],
  [  head,      1.0,         aes256_sha,  true,    chrome,     heartland_ip,   heartland,        ],
  [  head,      1.1,         aes256_sha,  true,    chrome,     heartland_ip,   heartland,        ],
  [  head,      1.2,         aes256_sha,  true,    chrome,     heartland_ip,   heartland,        ],
  [  head,      1.0,         aes256_sha,  false,   chrome,     heartland_ip,   heartland,        ],
  [  head,      1.1,         aes256_sha,  false,   chrome,     heartland_ip,   heartland,        ],
  [  head,      1.2,         aes256_sha,  false,   chrome,     heartland_ip,   heartland,        ],
  [  get,       1.0,         aes256_sha,  true,    chrome,     heartland_ip,   heartland_ip,     ],
  [  get,       1.1,         aes256_sha,  true,    chrome,     heartland_ip,   heartland_ip,     ],
  [  get,       1.2,         aes256_sha,  true,    chrome,     heartland_ip,   heartland_ip,     ],
  [  get,       1.0,         aes256_sha,  false,   chrome,     heartland_ip,   heartland_ip,     ],
  [  get,       1.1,         aes256_sha,  false,   chrome,     heartland_ip,   heartland_ip,     ],
  [  get,       1.2,         aes256_sha,  false,   chrome,     heartland_ip,   heartland_ip,     ],
  [  head,      1.0,         aes256_sha,  true,    chrome,     heartland_ip,   heartland_ip,     ],
  [  head,      1.1,         aes256_sha,  true,    chrome,     heartland_ip,   heartland_ip,     ],
  [  head,      1.2,         aes256_sha,  true,    chrome,     heartland_ip,   heartland_ip,     ],
  [  head,      1.0,         aes256_sha,  false,   chrome,     heartland_ip,   heartland_ip,     ],
  [  head,      1.1,         aes256_sha,  false,   chrome,     heartland_ip,   heartland_ip,     ],
  [  head,      1.2,         aes256_sha,  false,   chrome,     heartland_ip,   heartland_ip,     ],
  [  get,       1.0,         aes256_sha,  true,    chrome,     heartland_ip,   www_heartland,    ],
  [  get,       1.1,         aes256_sha,  true,    chrome,     heartland_ip,   www_heartland,    ],
  [  get,       1.2,         aes256_sha,  true,    chrome,     heartland_ip,   www_heartland,    ],
  [  get,       1.0,         aes256_sha,  false,   chrome,     heartland_ip,   www_heartland,    ],
  [  get,       1.1,         aes256_sha,  false,   chrome,     heartland_ip,   www_heartland,    ],
  [  get,       1.2,         aes256_sha,  false,   chrome,     heartland_ip,   www_heartland,    ],
  [  head,      1.0,         aes256_sha,  true,    chrome,     heartland_ip,   www_heartland,    ],
  [  head,      1.1,         aes256_sha,  true,    chrome,     heartland_ip,   www_heartland,    ],
  [  head,      1.2,         aes256_sha,  true,    chrome,     heartland_ip,   www_heartland,    ],
  [  head,      1.0,         aes256_sha,  false,   chrome,     heartland_ip,   www_heartland,    ],
  [  head,      1.1,         aes256_sha,  false,   chrome,     heartland_ip,   www_heartland,    ],
  [  head,      1.2,         aes256_sha,  false,   chrome,     heartland_ip,   www_heartland,    ],

]


def curl_command(http_verb, tls, cipher, is_secure, user_agent, host, header_host, trace_file: TRACE_FILE)
  http_verb_opt = "--#{http_verb}"
  tls_opt = "--tlsv#{tls}"
  cipher_opt = "--ciphers '#{cipher}'" if cipher
  is_secure_opt = "--insecure" unless is_secure
  user_agent_opt = "--user-agent '#{user_agent}'" if user_agent
  header_host_opt = "--header 'Host: #{header_host}'" if header_host

  "curl --trace-ascii #{trace_file} --silent #{http_verb_opt} #{tls_opt} #{cipher_opt} #{is_secure_opt} #{user_agent_opt} #{header_host_opt} https://#{host}"
end


def run_cmd_read_err_out(cmd, trace_file: TRACE_FILE)
  File.delete(trace_file) if File.exists?(trace_file)
  out, _, process = Open3.capture3(cmd)
  trace = IO.read(trace_file) if File.exists?(trace_file)
  File.delete(trace_file) if File.exists?(trace_file)
  { stdout: out, trace: trace, exitstatus: process.exitstatus }
end


def format_yaml(params, result, time: Time.now)
  [{ curl: curl_command(*params) }
    .merge(PARAM_KEYS.zip(params).to_h)
    .merge(result)
    .merge(
      time:   time.iso8601,
  )].to_yaml
end

try = [head, 1.0, rc4_sha, true, chrome, www_heartland, nil]

puts curl_command(*try)
result = run_cmd_read_err_out(curl_command(*try))
puts format_yaml(try, result)
